# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

pool:
  vmImage: 'VS2017-Win2016'
  demands:
    - DotNetFramework
    - msbuild
    - visualstudio
    - vstest
    - java

variables:
  solution: 'DFC.Digital/DFC.Digital.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0

- task: NuGetRestore@1
  displayName: 'NuGet restore'
  inputs:
    solution: DFC.Digital/DFC.Digital.sln
    selectOrConfig: config
    nugetConfigPath: DFC.Digital/.nuget/NuGet.Config

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'cd $Env:BUILD_SOURCESDIRECTORY
      Get-ChildItem -Filter "*.config.template" -Recurse | Rename-Item -NewName {$_.name -replace ''.config.template'',''.config'' }'

- task: VSBuild@1
  displayName: 'Build solution DFC.Digital/Seleno.BrowserStack.SpecFlowPlugin.sln'
  inputs:
    solution: DFC.Digital/Seleno.BrowserStack.SpecFlowPlugin.sln
    platform: 'Any CPU'
    configuration: Release

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: '$(SonarCloud)'
    organization: 'muthuramana-github'
    scannerMode: 'MSBuild'
    projectKey: '$(SonarCloudKey)'
    projectName: 'mk-dfc-digital'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'


- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'